### ISSUE TITLE
The visual studio project file for Weighted Blended OIT sample is missing.

### ISSUE THREAD

**Issue by waynehong666** [NVIDIAGameWorks/GraphicsSamples#2]
The visual studio project file for Weighted Blended OIT sample is missing. Is the sample code of WB OIT working?

**Comment by burningreggae** [comment]
i'm searching for the same

**Comment by larsbishop** [comment]
Indeed - that seems to be missing in the 3.0 release.  Assigned to myself to push an update.

**Comment by larsbishop** [comment]
I think  80e8ba8 (just pushed) should fix this issue on all platforms.
