### ISSUE TITLE
ShapedText sample doesn't work in glPathGlyphIndexRangeNV mode

### ISSUE THREAD

**Issue by sasmaster** [NVIDIAGameWorks/GraphicsSamples#4]
The sample by default uses an older API.
Once I comment our 

   ` #define PRE_glPathGlyphIndexRangeNV`

The sample doesn't work.First issue I solved.I had to load function pointer by myself for methods:
 ```
 glPathGlyphIndexArrayNV
 glPathMemoryGlyphIndexArrayNV
 glPathGlyphIndexRangeNV

```

But then the 
           ```
   fontStatus = glPathGlyphIndexArrayNV(nvpr_glyph_base[ii],
                    GL_FILE_NAME_NV, font_names[ii], /*fontStyle */0,
                    /*firstGlyphIndex*/0, ft_face->num_glyphs,
                    path_template, EM_SCALE);
```

Returns error    GL_FONT_TARGET_UNAVAILABLE_NV

Please fix it.Thanks

**Comment by sasmaster** [comment]
And I am running  on the latest driver 382.53 ,GTX970

**Comment by larsbishop** [comment]
We'll take a look - hopefully this week.

**Comment by larsbishop** [comment]
I can repro the issue (both the missing function queries and the error once the function queries are in place).  We are debugging now.

**Comment by sasmaster** [comment]
Great  thanks. Looking forward for the fix  :)

**Comment by sasmaster** [comment]
Hi Guys.Any info when the fix will be available?

**Comment by larsbishop** [comment]
Sorry for the delay.  US long weekend and the unavailability of the expert on these APIs has delayed things a bit.  I'm on it, however.

**Comment by larsbishop** [comment]
https://github.com/NVIDIAGameWorks/GraphicsSamples/commit/c5b600c19e7b292d6685d221d8ca46a7a8fc0a81 is an attempt to fix this and clarify the situation.  Basically, on Windows, if you want to use the optional feature of loading fonts from file, you must ensure that FreeType from GTK3 (and all of its dependent DLLs) for the particular 32/64 build flavor must be in the system path, AND (for now) it must be named freetype6.dll.  For now, the developer must provide the freetype6.dll (and dependencies).  Several independent Windows builds of these are available on the web.  We have tested locally with win32 and x64 builds, and the samples function.  Note that the file reading case is still commented out by default.  Also, note that in general, the more portable option is likely to use the system font paths.
